### ISSUE TITLE
Add ability to track who you blocked and why

### ISSUE THREAD

**Issue by lkarvec** [MobileFirstLLC/doucheblock#20]
Good for both debugging purposes and to inform the user of what the program is doing.

EX:

**Blocklist** : he, she, they

**Blocked**:  Randy @randall120478509824 - "he" [word the program caught] - he/him amogusamogusamogusamogus[copy paste of their bio].

**Comment by nkrusch** [comment]
Could add a log of blocks, and link to it from settings and/or context menu. Some TODOs:

Figure out where to store it

- is there a browser API to write to disk from extension
- if not, can always use storage but perhaps with some cap (e.g. last 100 entries) so it does not grow infinitely

Edge cases

It may not be great if user has many devices and expect to see the same experience between those devices if storing only locally. This may not be a real concern; Firefox and opera are already local only because of the storage implementation.
